openapi: 3.0.2
info:
  title: eMSP-BookingManagementService
  version: 1.0.0
  description: Api for eMSP-BookingManagementService
tags:
  - name: booking
    description: Booking operations
paths:
  '/customer/{customerId}/booking':
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Booking'
          description: ''
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
      security:
        - Authenticated: []
      tags:
        - booking
      operationId: getAllBookings
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookingRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
          description: ''
        '400':
          $ref: '#/components/responses/ErrorResponse'
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '409':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
      security:
        - Authenticated: []
      tags:
        - booking
      operationId: postBooking
    parameters:
      - name: customerId
        schema:
          format: int64
          type: integer
        in: path
        required: true
  '/customer/{customerId}/booking/status':
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BookingStatus'
          description: ''
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
      security:
        - Authenticated: []
      tags:
        - booking
      operationId: getAllBookingStatuses
      parameters:
        - name: customerId
          schema:
            format: int64
            type: integer
          in: path
          required: true
  '/customer/{customerId}/booking/{bookingCode}':
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
          description: ''
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
      security:
        - Authenticated: []
      tags:
        - booking
      operationId: getBooking
    parameters:
      - name: customerId
        schema:
          format: int64
          type: integer
        in: path
        required: true
      - name: bookingCode
        schema:
          format: int64
          type: integer
        in: path
        required: true
  '/customer/{customerId}/booking/{bookingCode}/status':
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingStatus'
          description: ''
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
      security:
        - Authenticated: []
      tags:
        - booking
      description: ''
      operationId: getBookingStatus
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookingStatus'
        required: true
      responses:
        '200':
          description: ''
        '401':
          $ref: '#/components/responses/ErrorResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '409':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
      security:
        - Authenticated: []
      tags:
        - booking
      operationId: putBookingStatus
    parameters:
      - name: customerId
        schema:
          format: int64
          type: integer
        in: path
        required: true
      - name: bookingCode
        schema:
          format: int64
          type: integer
        in: path
        required: true
  '/customer/{customerId}/notificationInfo':
    parameters:
      - schema:
          type: integer
          format: int64
        name: customerId
        in: path
        required: true
    post:
      summary: Register device
      operationId: registerDevice
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                expoToken:
                  type: string
              required:
                - expoToken
      tags:
        - booking
      description: ''
components:
  schemas:
    Timeframe:
      required:
        - startInstant
      type: object
      properties:
        startInstant:
          format: date-time
          type: string
        endInstant:
          format: date-time
          type: string
      example:
        startInstant: '2018-11-13T20:20:39+00:00'
        endInstant: '2018-11-13T20:20:39+00:00'
      x-examples:
        Example 1:
          startInstant: '2018-11-13T20:20:39+00:00'
          endInstant: '2018-11-13T20:20:39+00:00'
    SocketType:
      type: string
      enum:
        - SLOW
        - FAST
        - RAPID
      x-examples:
        Example 1: SLOW
    BookingType:
      type: string
      enum:
        - IN_ADVANCE
        - ON_THE_FLY
      example: IN_ADVANCE
      x-examples:
        Example 1: IN_ADVANCE
    BookingRequest:
      type: object
      oneOf:
        - $ref: '#/components/schemas/BookingInAdvance'
        - $ref: '#/components/schemas/BookingOnTheFly'
      discriminator:
        propertyName: bookingType
      description: ''
      x-examples:
        Example 1:
          bookingType: IN_ADVANCE
          socketType: SLOW
          timeframe:
            startInstant: '2018-11-13T20:20:39+00:00'
            endInstant: '2018-11-13T20:20:39+00:00'
        Example 2:
          bookingType: BookingInAdvance
          socketType: SLOW
          timeframe:
            startInstant: '2018-11-13T20:20:39+00:00'
            endInstant: '2018-11-13T20:20:39+00:00'
    BookingInAdvance:
      required:
        - bookingType
        - socketType
        - customerId
        - chargingStationId
        - timeframe
      type: object
      properties:
        bookingType:
          type: string
          x-discriminator: BookingInAdvance
        customerId:
          format: int64
          type: integer
        chargingStationId:
          format: int64
          type: integer
        socketType:
          $ref: '#/components/schemas/SocketType'
        timeframe:
          $ref: '#/components/schemas/Timeframe'
      example:
        bookingType: BookingInAdvance
        socketType: SLOW
        customerId: 1
        chargingStationId: 1
        timeframe:
          startInstant: '2018-11-13T20:20:39+00:00'
          endInstant: '2018-11-13T20:20:39+00:00'
      x-examples:
        Example 1:
          bookingType: BookingInAdvance
          socketType: SLOW
          timeframe:
            startInstant: '2018-11-13T20:20:39+00:00'
            endInstant: '2018-11-13T20:20:39+00:00'
    BookingOnTheFly:
      required:
        - bookingType
        - customerId
        - chargingStationId
        - chargingPointId
        - socketId
      type: object
      properties:
        bookingType:
          type: string
          x-discriminator: BookingOnTheFly
        customerId:
          format: int64
          type: integer
        chargingStationId:
          format: int64
          type: integer
        chargingPointId:
          format: int64
          description: ''
          type: integer
        socketId:
          format: int64
          description: ''
          type: integer
      example:
        bookingType: BookingOnTheFly
        customerId: 1
        chargingStationId: 1
        chargingPointId: 1
        socketId: 1
      x-examples:
        Example 1:
          bookingType: BookingOnTheFly
          chargingPointId: 1
          socketId: 1
    BookingStatusCancelled:
      type: object
      required:
        - bookingStatus
        - bookingId
      properties:
        bookingStatus:
          type: string
          x-discriminator: BookingStatusCancelled
        bookingId:
          type: integer
          format: int64
      example:
        bookingStatus: BookingStatusCancelled
        bookingId: 1
      x-examples:
        Example 1:
          bookingStatus: BookingStatusCancelled
    BookingStatusCompleted:
      type: object
      required:
        - bookingStatus
        - bookingId
      properties:
        bookingStatus:
          type: string
          x-discriminator: BookingStatusCompleted
        bookingId:
          type: integer
          format: int64
      example:
        bookingStatus: BookingStatusCompleted
        bookingId: 1
      x-examples:
        Example 1:
          bookingStatus: BookingStatusCompleted
    BookingStatusExpired:
      type: object
      example:
        bookingStatus: BookingStatusExpired
        bookingId: 1
      required:
        - bookingStatus
        - bookingId
      properties:
        bookingStatus:
          type: string
          x-discriminator: BookingStatusExpired
        bookingId:
          type: integer
          format: int64
      x-examples:
        Example 1:
          bookingStatus: BookingStatusExpired
          bookingId: 1
    BookingStatusInProgress:
      type: object
      required:
        - bookingStatus
        - bookingId
      properties:
        bookingStatus:
          type: string
          x-discriminator: BookingStatusInProgress
        bookingId:
          type: integer
          format: int64
        expectedMinutesLeft:
          format: int32
          type: integer
      example:
        bookingStatus: BookingStatusInProgress
        bookingId: 1
        expectedMinutesLeft: 1
      x-examples:
        Example 1:
          bookingStatus: BookingStatusInProgress
          expectedMinutesLeft: 1
    BookingStatusPlanned:
      type: object
      required:
        - bookingStatus
        - bookingId
      properties:
        bookingStatus:
          x-discriminator: BookingStatusPlanned
          type: string
        bookingId:
          type: integer
          format: int64
      example:
        bookingStatus: BookingStatusPlanned
        bookingId: 1
      x-examples:
        Example 1:
          bookingStatus: BookingStatusPlanned
    BookingStatus:
      oneOf:
        - $ref: '#/components/schemas/BookingStatusInProgress'
        - $ref: '#/components/schemas/BookingStatusPlanned'
        - $ref: '#/components/schemas/BookingStatusExpired'
        - $ref: '#/components/schemas/BookingStatusCancelled'
        - $ref: '#/components/schemas/BookingStatusCompleted'
      discriminator:
        propertyName: bookingStatus
      type: object
    Error:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        status:
          format: int32
          type: integer
        detail:
          type: string
        instance:
          type: string
      example:
        type: /errors/overlapping-booking-request
        title: Overlapping booking request
        status: 409
        detail: The requested booking timeframe overlaps with another planned booking.
        instance: /booking
    Booking:
      required:
        - bookingId
        - bookingCode
        - bookingType
        - chargingPointId
        - chargingStationId
        - customerId
        - socketId
        - socketType
        - timeframe
      type: object
      properties:
        bookingId:
          format: int64
          type: integer
          readOnly: true
        bookingCode:
          type: string
          readOnly: true
        customerId:
          format: int64
          type: integer
          readOnly: true
        chargingStationId:
          format: int64
          type: integer
          readOnly: true
        chargingPointId:
          format: int64
          type: integer
          readOnly: true
        socketId:
          format: int64
          type: integer
          readOnly: true
        socketType:
          $ref: '#/components/schemas/SocketType'
        timeframe:
          $ref: '#/components/schemas/Timeframe'
        bookingType:
          $ref: '#/components/schemas/BookingType'
      example:
        bookingId: 127
        bookingCode: '1'
        customerId: 1
        chargingStationId: 1
        bookingType: IN_ADVANCE
        chargingPointId: 1
        socketId: 1
        socketType: SLOW
        timeframe:
          startInstant: '2018-11-13T20:20:39+00:00'
          endInstant: '2018-11-13T20:20:39+00:00'
  responses:
    ErrorResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: ''
  securitySchemes:
    Authenticated:
      scheme: bearer
      type: http
servers:
  - url: 'http://booking-management-service'
    description: ''
